# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/afar/Project_IP_Telephony_Python_Voip/JaroEliCall/gui/adduser.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FormInterface(object):
    def setupUi(self, FormInterface):
        FormInterface.setObjectName("FormInterface")
        FormInterface.resize(781, 500)
        self.horizontalLayout = QtWidgets.QHBoxLayout(FormInterface)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontal_layout_main = QtWidgets.QHBoxLayout()
        self.horizontal_layout_main.setSpacing(0)
        self.horizontal_layout_main.setObjectName("horizontal_layout_main")
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontal_layout_main.addItem(spacerItem)
        self.vertical_layout_left = QtWidgets.QVBoxLayout()
        self.vertical_layout_left.setObjectName("vertical_layout_left")
        self.label_list_users = QtWidgets.QLabel(FormInterface)
        self.label_list_users.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_list_users.setObjectName("label_list_users")
        self.vertical_layout_left.addWidget(self.label_list_users)
        self.table_widget_list_of_users = QtWidgets.QTableWidget(FormInterface)
        self.table_widget_list_of_users.setMinimumSize(QtCore.QSize(400, 100))
        self.table_widget_list_of_users.setMaximumSize(QtCore.QSize(500, 16777215))
        self.table_widget_list_of_users.setBaseSize(QtCore.QSize(300, 100))
        self.table_widget_list_of_users.setAutoFillBackground(False)
        self.table_widget_list_of_users.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.table_widget_list_of_users.setMidLineWidth(1)
        self.table_widget_list_of_users.setAutoScroll(False)
        self.table_widget_list_of_users.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.table_widget_list_of_users.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.table_widget_list_of_users.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.table_widget_list_of_users.setIconSize(QtCore.QSize(20, 20))
        self.table_widget_list_of_users.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.table_widget_list_of_users.setObjectName("table_widget_list_of_users")
        self.table_widget_list_of_users.setColumnCount(3)
        self.table_widget_list_of_users.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_list_of_users.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_list_of_users.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_list_of_users.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_list_of_users.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_list_of_users.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_list_of_users.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_list_of_users.setItem(0, 2, item)
        self.table_widget_list_of_users.horizontalHeader().setCascadingSectionResizes(True)
        self.table_widget_list_of_users.horizontalHeader().setDefaultSectionSize(100)
        self.table_widget_list_of_users.verticalHeader().setMinimumSectionSize(100)
        self.vertical_layout_left.addWidget(self.table_widget_list_of_users)
        self.label_info = QtWidgets.QLabel(FormInterface)
        self.label_info.setText("")
        self.label_info.setObjectName("label_info")
        self.vertical_layout_left.addWidget(self.label_info)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.push_button_call = QtWidgets.QPushButton(FormInterface)
        self.push_button_call.setObjectName("push_button_call")
        self.horizontalLayout_5.addWidget(self.push_button_call)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.push_button_invite = QtWidgets.QPushButton(FormInterface)
        self.push_button_invite.setObjectName("push_button_invite")
        self.horizontalLayout_5.addWidget(self.push_button_invite)
        self.vertical_layout_left.addLayout(self.horizontalLayout_5)
        self.horizontal_layout_main.addLayout(self.vertical_layout_left)
        spacerItem2 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontal_layout_main.addItem(spacerItem2)
        self.vertical_layout_right = QtWidgets.QVBoxLayout()
        self.vertical_layout_right.setObjectName("vertical_layout_right")
        self.push_button_logout = QtWidgets.QPushButton(FormInterface)
        self.push_button_logout.setObjectName("push_button_logout")
        self.vertical_layout_right.addWidget(self.push_button_logout)
        self.label_avatar = QtWidgets.QLabel(FormInterface)
        self.label_avatar.setMinimumSize(QtCore.QSize(100, 100))
        self.label_avatar.setText("")
        self.label_avatar.setPixmap(QtGui.QPixmap("icons/111317-essential-ui/svg/edit-profile.svg"))
        self.label_avatar.setScaledContents(False)
        self.label_avatar.setAlignment(QtCore.Qt.AlignCenter)
        self.label_avatar.setIndent(0)
        self.label_avatar.setObjectName("label_avatar")
        self.vertical_layout_right.addWidget(self.label_avatar)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.vertical_layout_right.addItem(spacerItem3)
        self.horizontal_layout_main.addLayout(self.vertical_layout_right)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontal_layout_main.addItem(spacerItem4)
        spacerItem5 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontal_layout_main.addItem(spacerItem5)
        self.horizontalLayout.addLayout(self.horizontal_layout_main)

        self.retranslateUi(FormInterface)
        QtCore.QMetaObject.connectSlotsByName(FormInterface)
        FormInterface.setTabOrder(self.table_widget_list_of_users, self.push_button_call)
        FormInterface.setTabOrder(self.push_button_call, self.push_button_invite)
        FormInterface.setTabOrder(self.push_button_invite, self.push_button_logout)

    def retranslateUi(self, FormInterface):
        _translate = QtCore.QCoreApplication.translate
        FormInterface.setWindowTitle(_translate("FormInterface", "Form"))
        self.label_list_users.setText(_translate("FormInterface", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">Lista użytkowników</span></p></body></html>"))
        self.table_widget_list_of_users.setSortingEnabled(True)
        item = self.table_widget_list_of_users.horizontalHeaderItem(0)
        item.setText(_translate("FormInterface", "Kto"))
        item = self.table_widget_list_of_users.horizontalHeaderItem(1)
        item.setText(_translate("FormInterface", "Status"))
        item = self.table_widget_list_of_users.horizontalHeaderItem(2)
        item.setText(_translate("FormInterface", "Awatar"))
        __sortingEnabled = self.table_widget_list_of_users.isSortingEnabled()
        self.table_widget_list_of_users.setSortingEnabled(False)
        item = self.table_widget_list_of_users.item(0, 0)
        item.setText(_translate("FormInterface", "Ania"))
        item = self.table_widget_list_of_users.item(0, 1)
        item.setText(_translate("FormInterface", "Online"))
        item = self.table_widget_list_of_users.item(0, 2)
        item.setText(_translate("FormInterface", "pic1"))
        self.table_widget_list_of_users.setSortingEnabled(__sortingEnabled)
        self.push_button_call.setText(_translate("FormInterface", "Zadzwoń"))
        self.push_button_invite.setText(_translate("FormInterface", "Zaproś do pokoju"))
        self.push_button_logout.setText(_translate("FormInterface", "Wyloguj"))

