# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/afar/Project_IP_Telephony_Python_Voip/JaroEliCall/gui/call.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_CallDialog(object):
    def setupUi(self, CallDialog):
        CallDialog.setObjectName("CallDialog")
        CallDialog.resize(762, 488)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(CallDialog)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontal_layout_main = QtWidgets.QHBoxLayout()
        self.horizontal_layout_main.setObjectName("horizontal_layout_main")
        self.vertical_layout_user_1 = QtWidgets.QVBoxLayout()
        self.vertical_layout_user_1.setObjectName("vertical_layout_user_1")
        self.frame_user_1 = QtWidgets.QFrame(CallDialog)
        self.frame_user_1.setMinimumSize(QtCore.QSize(150, 150))
        self.frame_user_1.setMaximumSize(QtCore.QSize(150, 150))
        self.frame_user_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_user_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_user_1.setObjectName("frame_user_1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_user_1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_avatar_user_1 = QtWidgets.QLabel(self.frame_user_1)
        self.label_avatar_user_1.setMinimumSize(QtCore.QSize(0, 0))
        self.label_avatar_user_1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_avatar_user_1.setObjectName("label_avatar_user_1")
        self.verticalLayout_2.addWidget(self.label_avatar_user_1)
        self.vertical_layout_user_1.addWidget(self.frame_user_1)
        self.label_name_user_1 = QtWidgets.QLabel(CallDialog)
        self.label_name_user_1.setMinimumSize(QtCore.QSize(0, 20))
        self.label_name_user_1.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_name_user_1.setObjectName("label_name_user_1")
        self.vertical_layout_user_1.addWidget(self.label_name_user_1)
        self.horizontal_layout_main.addLayout(self.vertical_layout_user_1)
        self.vertical_layout_user_2 = QtWidgets.QVBoxLayout()
        self.vertical_layout_user_2.setObjectName("vertical_layout_user_2")
        self.frame_user_2 = QtWidgets.QFrame(CallDialog)
        self.frame_user_2.setMinimumSize(QtCore.QSize(150, 150))
        self.frame_user_2.setMaximumSize(QtCore.QSize(150, 150))
        self.frame_user_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_user_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_user_2.setObjectName("frame_user_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_user_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_avatar_user_2 = QtWidgets.QLabel(self.frame_user_2)
        self.label_avatar_user_2.setMinimumSize(QtCore.QSize(0, 0))
        self.label_avatar_user_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_avatar_user_2.setObjectName("label_avatar_user_2")
        self.verticalLayout_5.addWidget(self.label_avatar_user_2)
        self.vertical_layout_user_2.addWidget(self.frame_user_2)
        self.label_name_user_2 = QtWidgets.QLabel(CallDialog)
        self.label_name_user_2.setMinimumSize(QtCore.QSize(0, 20))
        self.label_name_user_2.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_name_user_2.setObjectName("label_name_user_2")
        self.vertical_layout_user_2.addWidget(self.label_name_user_2)
        self.horizontal_layout_main.addLayout(self.vertical_layout_user_2)
        self.verticalLayout_6.addLayout(self.horizontal_layout_main)
        self.frame_bar = QtWidgets.QFrame(CallDialog)
        self.frame_bar.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_bar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_bar.setObjectName("frame_bar")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_bar)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontal_layout_bar = QtWidgets.QHBoxLayout()
        self.horizontal_layout_bar.setObjectName("horizontal_layout_bar")
        self.horizontal_layout_view = QtWidgets.QHBoxLayout()
        self.horizontal_layout_view.setObjectName("horizontal_layout_view")
        self.push_button_room = QtWidgets.QPushButton(self.frame_bar)
        self.push_button_room.setObjectName("push_button_room")
        self.horizontal_layout_view.addWidget(self.push_button_room)
        self.push_button_add_user = QtWidgets.QPushButton(self.frame_bar)
        self.push_button_add_user.setObjectName("push_button_add_user")
        self.horizontal_layout_view.addWidget(self.push_button_add_user)
        self.horizontal_layout_bar.addLayout(self.horizontal_layout_view)
        self.horizontal_layout_managment = QtWidgets.QHBoxLayout()
        self.horizontal_layout_managment.setObjectName("horizontal_layout_managment")
        self.push_button_settings = QtWidgets.QPushButton(self.frame_bar)
        self.push_button_settings.setObjectName("push_button_settings")
        self.horizontal_layout_managment.addWidget(self.push_button_settings)
        self.push_button_done = QtWidgets.QPushButton(self.frame_bar)
        self.push_button_done.setObjectName("push_button_done")
        self.horizontal_layout_managment.addWidget(self.push_button_done)
        self.push_button_logout = QtWidgets.QPushButton(self.frame_bar)
        self.push_button_logout.setObjectName("push_button_logout")
        self.horizontal_layout_managment.addWidget(self.push_button_logout)
        self.horizontal_layout_bar.addLayout(self.horizontal_layout_managment)
        self.verticalLayout.addLayout(self.horizontal_layout_bar)
        self.verticalLayout_6.addWidget(self.frame_bar)

        self.retranslateUi(CallDialog)
        QtCore.QMetaObject.connectSlotsByName(CallDialog)

    def retranslateUi(self, CallDialog):
        _translate = QtCore.QCoreApplication.translate
        CallDialog.setWindowTitle(_translate("CallDialog", "Dialog"))
        self.label_avatar_user_1.setText(_translate("CallDialog", "Me"))
        self.label_name_user_1.setText(_translate("CallDialog", "Uzyszkodnik"))
        self.label_avatar_user_2.setText(_translate("CallDialog", "User1"))
        self.label_name_user_2.setText(_translate("CallDialog", "User1"))
        self.push_button_room.setText(_translate("CallDialog", "pokój"))
        self.push_button_add_user.setText(_translate("CallDialog", "dodaj rozmówce"))
        self.push_button_settings.setText(_translate("CallDialog", "ustawienia"))
        self.push_button_done.setText(_translate("CallDialog", "rozłącz"))
        self.push_button_logout.setText(_translate("CallDialog", "wyloguj"))

