# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/afar/Project_IP_Telephony_Python_Voip/JaroEliCall/gui/ui/main.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainInterfaceDialog(object):
    def setupUi(self, MainInterfaceDialog):
        MainInterfaceDialog.setObjectName("MainInterfaceDialog")
        MainInterfaceDialog.resize(530, 498)
        MainInterfaceDialog.setMinimumSize(QtCore.QSize(530, 498))
        self.horizontalLayout = QtWidgets.QHBoxLayout(MainInterfaceDialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontal_layout_main = QtWidgets.QHBoxLayout()
        self.horizontal_layout_main.setSpacing(0)
        self.horizontal_layout_main.setObjectName("horizontal_layout_main")
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontal_layout_main.addItem(spacerItem)
        self.vertical_layout_left = QtWidgets.QVBoxLayout()
        self.vertical_layout_left.setObjectName("vertical_layout_left")
        self.label_list_users = QtWidgets.QLabel(MainInterfaceDialog)
        self.label_list_users.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_list_users.setObjectName("label_list_users")
        self.vertical_layout_left.addWidget(self.label_list_users)
        self.label_info = QtWidgets.QLabel(MainInterfaceDialog)
        self.label_info.setText("")
        self.label_info.setObjectName("label_info")
        self.vertical_layout_left.addWidget(self.label_info)
        self.table_widget_list_of_users = QtWidgets.QTableWidget(MainInterfaceDialog)
        self.table_widget_list_of_users.setMinimumSize(QtCore.QSize(400, 100))
        self.table_widget_list_of_users.setMaximumSize(QtCore.QSize(500, 16777215))
        self.table_widget_list_of_users.setBaseSize(QtCore.QSize(300, 100))
        self.table_widget_list_of_users.setAutoFillBackground(False)
        self.table_widget_list_of_users.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.table_widget_list_of_users.setMidLineWidth(1)
        self.table_widget_list_of_users.setAutoScroll(False)
        self.table_widget_list_of_users.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.table_widget_list_of_users.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.table_widget_list_of_users.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.table_widget_list_of_users.setIconSize(QtCore.QSize(20, 20))
        self.table_widget_list_of_users.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.table_widget_list_of_users.setObjectName("table_widget_list_of_users")
        self.table_widget_list_of_users.setColumnCount(3)
        self.table_widget_list_of_users.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_list_of_users.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget_list_of_users.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setText("Awatar")
        font = QtGui.QFont()
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.table_widget_list_of_users.setHorizontalHeaderItem(2, item)
        self.table_widget_list_of_users.horizontalHeader().setCascadingSectionResizes(True)
        self.table_widget_list_of_users.horizontalHeader().setDefaultSectionSize(100)
        self.table_widget_list_of_users.verticalHeader().setMinimumSectionSize(100)
        self.vertical_layout_left.addWidget(self.table_widget_list_of_users)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.push_button_call = QtWidgets.QPushButton(MainInterfaceDialog)
        self.push_button_call.setObjectName("push_button_call")
        self.horizontalLayout_5.addWidget(self.push_button_call)
        self.push_button_invite = QtWidgets.QPushButton(MainInterfaceDialog)
        self.push_button_invite.setObjectName("push_button_invite")
        self.horizontalLayout_5.addWidget(self.push_button_invite)
        self.vertical_layout_left.addLayout(self.horizontalLayout_5)
        self.horizontal_layout_main.addLayout(self.vertical_layout_left)
        spacerItem1 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontal_layout_main.addItem(spacerItem1)
        self.vertical_layout_right = QtWidgets.QVBoxLayout()
        self.vertical_layout_right.setObjectName("vertical_layout_right")
        self.label_avatar = QtWidgets.QLabel(MainInterfaceDialog)
        self.label_avatar.setMinimumSize(QtCore.QSize(75, 75))
        self.label_avatar.setObjectName("label_avatar")
        self.vertical_layout_right.addWidget(self.label_avatar)
        self.label_user_name = QtWidgets.QLabel(MainInterfaceDialog)
        self.label_user_name.setObjectName("label_user_name")
        self.vertical_layout_right.addWidget(self.label_user_name)
        self.push_button_logout = QtWidgets.QPushButton(MainInterfaceDialog)
        self.push_button_logout.setObjectName("push_button_logout")
        self.vertical_layout_right.addWidget(self.push_button_logout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.vertical_layout_right.addItem(spacerItem2)
        self.horizontal_layout_main.addLayout(self.vertical_layout_right)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontal_layout_main.addItem(spacerItem3)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontal_layout_main.addItem(spacerItem4)
        self.horizontalLayout.addLayout(self.horizontal_layout_main)

        self.retranslateUi(MainInterfaceDialog)
        QtCore.QMetaObject.connectSlotsByName(MainInterfaceDialog)
        MainInterfaceDialog.setTabOrder(self.table_widget_list_of_users, self.push_button_call)
        MainInterfaceDialog.setTabOrder(self.push_button_call, self.push_button_invite)
        MainInterfaceDialog.setTabOrder(self.push_button_invite, self.push_button_logout)

    def retranslateUi(self, MainInterfaceDialog):
        _translate = QtCore.QCoreApplication.translate
        MainInterfaceDialog.setWindowTitle(_translate("MainInterfaceDialog", "JaroEliCall"))
        self.label_list_users.setText(_translate("MainInterfaceDialog", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">Lista użytkowników</span></p></body></html>"))
        self.table_widget_list_of_users.setSortingEnabled(True)
        item = self.table_widget_list_of_users.horizontalHeaderItem(0)
        item.setText(_translate("MainInterfaceDialog", "Kto"))
        item = self.table_widget_list_of_users.horizontalHeaderItem(1)
        item.setText(_translate("MainInterfaceDialog", "Status"))
        self.push_button_call.setText(_translate("MainInterfaceDialog", "Zadzwoń"))
        self.push_button_invite.setText(_translate("MainInterfaceDialog", "Zaproś do pokoju"))
        self.label_avatar.setText(_translate("MainInterfaceDialog", "Avatar"))
        self.label_user_name.setText(_translate("MainInterfaceDialog", "User name"))
        self.push_button_logout.setText(_translate("MainInterfaceDialog", "Wyloguj"))

