# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/afar/Project_IP_Telephony_Python_Voip/JaroEliCall/gui/main_interface.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindowInterface(object):
    def setupUi(self, MainWindowInterface):
        MainWindowInterface.setObjectName("MainWindowInterface")
        MainWindowInterface.resize(567, 381)
        MainWindowInterface.setMinimumSize(QtCore.QSize(0, 0))
        MainWindowInterface.setMaximumSize(QtCore.QSize(16777215, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/115873-filled-management-elements/png/speech-1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindowInterface.setWindowIcon(icon)
        MainWindowInterface.setIconSize(QtCore.QSize(0, 0))
        self.central_widget = QtWidgets.QWidget(MainWindowInterface)
        self.central_widget.setObjectName("central_widget")
        self.gridLayout = QtWidgets.QGridLayout(self.central_widget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_selected = QtWidgets.QLabel(self.central_widget)
        self.label_selected.setObjectName("label_selected")
        self.gridLayout.addWidget(self.label_selected, 1, 0, 1, 1)
        self.splitter = QtWidgets.QSplitter(self.central_widget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.tab_widget = QtWidgets.QTabWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_widget.sizePolicy().hasHeightForWidth())
        self.tab_widget.setSizePolicy(sizePolicy)
        self.tab_widget.setMinimumSize(QtCore.QSize(0, 0))
        self.tab_widget.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tab_widget.setAccessibleName("")
        self.tab_widget.setAutoFillBackground(False)
        self.tab_widget.setStyleSheet("")
        self.tab_widget.setLocale(QtCore.QLocale(QtCore.QLocale.Polish, QtCore.QLocale.Poland))
        self.tab_widget.setTabPosition(QtWidgets.QTabWidget.South)
        self.tab_widget.setIconSize(QtCore.QSize(16, 16))
        self.tab_widget.setElideMode(QtCore.Qt.ElideNone)
        self.tab_widget.setUsesScrollButtons(False)
        self.tab_widget.setDocumentMode(True)
        self.tab_widget.setTabsClosable(False)
        self.tab_widget.setMovable(False)
        self.tab_widget.setTabBarAutoHide(False)
        self.tab_widget.setObjectName("tab_widget")
        self.tab_users = QtWidgets.QWidget()
        self.tab_users.setObjectName("tab_users")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_users)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.vertical_layout_tab1 = QtWidgets.QVBoxLayout()
        self.vertical_layout_tab1.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.vertical_layout_tab1.setContentsMargins(-1, -1, -1, 3)
        self.vertical_layout_tab1.setSpacing(0)
        self.vertical_layout_tab1.setObjectName("vertical_layout_tab1")
        self.line_edit_search_users = QtWidgets.QLineEdit(self.tab_users)
        self.line_edit_search_users.setObjectName("line_edit_search_users")
        self.vertical_layout_tab1.addWidget(self.line_edit_search_users)
        self.list_of_users = QtWidgets.QListWidget(self.tab_users)
        self.list_of_users.setObjectName("list_of_users")
        self.vertical_layout_tab1.addWidget(self.list_of_users)
        self.verticalLayout_6.addLayout(self.vertical_layout_tab1)
        self.tab_widget.addTab(self.tab_users, "")
        self.tab_rooms = QtWidgets.QWidget()
        self.tab_rooms.setObjectName("tab_rooms")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_rooms)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 3)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.vertical_layout_tab2 = QtWidgets.QVBoxLayout()
        self.vertical_layout_tab2.setSpacing(0)
        self.vertical_layout_tab2.setObjectName("vertical_layout_tab2")
        self.line_edit_search_rooms = QtWidgets.QLineEdit(self.tab_rooms)
        self.line_edit_search_rooms.setObjectName("line_edit_search_rooms")
        self.vertical_layout_tab2.addWidget(self.line_edit_search_rooms)
        self.list_of_rooms = QtWidgets.QListWidget(self.tab_rooms)
        self.list_of_rooms.setObjectName("list_of_rooms")
        self.vertical_layout_tab2.addWidget(self.list_of_rooms)
        self.verticalLayout_5.addLayout(self.vertical_layout_tab2)
        self.tab_widget.addTab(self.tab_rooms, "")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.vertical_layout_info = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.vertical_layout_info.setContentsMargins(0, 0, 0, 0)
        self.vertical_layout_info.setSpacing(0)
        self.vertical_layout_info.setObjectName("vertical_layout_info")
        self.list_of_informations = QtWidgets.QListWidget(self.layoutWidget)
        self.list_of_informations.setBatchSize(100)
        self.list_of_informations.setObjectName("list_of_informations")
        self.vertical_layout_info.addWidget(self.list_of_informations)
        self.push_button_call = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.push_button_call.sizePolicy().hasHeightForWidth())
        self.push_button_call.setSizePolicy(sizePolicy)
        self.push_button_call.setFlat(False)
        self.push_button_call.setObjectName("push_button_call")
        self.vertical_layout_info.addWidget(self.push_button_call)
        self.gridLayout.addWidget(self.splitter, 2, 0, 2, 3)
        self.check_box_mute = QtWidgets.QCheckBox(self.central_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.check_box_mute.sizePolicy().hasHeightForWidth())
        self.check_box_mute.setSizePolicy(sizePolicy)
        self.check_box_mute.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.check_box_mute.setObjectName("check_box_mute")
        self.gridLayout.addWidget(self.check_box_mute, 1, 2, 1, 1)
        self.horizontal_layout_who_is_logged = QtWidgets.QHBoxLayout()
        self.horizontal_layout_who_is_logged.setSpacing(6)
        self.horizontal_layout_who_is_logged.setObjectName("horizontal_layout_who_is_logged")
        self.label_you_logged_as = QtWidgets.QLabel(self.central_widget)
        self.label_you_logged_as.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_you_logged_as.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_you_logged_as.setObjectName("label_you_logged_as")
        self.horizontal_layout_who_is_logged.addWidget(self.label_you_logged_as)
        self.label_user_name = QtWidgets.QLabel(self.central_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_user_name.sizePolicy().hasHeightForWidth())
        self.label_user_name.setSizePolicy(sizePolicy)
        self.label_user_name.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_user_name.setAlignment(QtCore.Qt.AlignCenter)
        self.label_user_name.setObjectName("label_user_name")
        self.horizontal_layout_who_is_logged.addWidget(self.label_user_name)
        self.gridLayout.addLayout(self.horizontal_layout_who_is_logged, 0, 1, 1, 2)
        MainWindowInterface.setCentralWidget(self.central_widget)
        self.status_bar = QtWidgets.QStatusBar(MainWindowInterface)
        self.status_bar.setObjectName("status_bar")
        MainWindowInterface.setStatusBar(self.status_bar)
        self.menu_bar = QtWidgets.QMenuBar(MainWindowInterface)
        self.menu_bar.setGeometry(QtCore.QRect(0, 0, 567, 30))
        self.menu_bar.setObjectName("menu_bar")
        self.menu = QtWidgets.QMenu(self.menu_bar)
        self.menu.setObjectName("menu")
        MainWindowInterface.setMenuBar(self.menu_bar)
        self.act_about = QtWidgets.QAction(MainWindowInterface)
        self.act_about.setObjectName("act_about")
        self.actionUstawienia = QtWidgets.QAction(MainWindowInterface)
        self.actionUstawienia.setObjectName("actionUstawienia")
        self.act_rooms = QtWidgets.QAction(MainWindowInterface)
        self.act_rooms.setObjectName("act_rooms")
        self.act_users = QtWidgets.QAction(MainWindowInterface)
        self.act_users.setObjectName("act_users")
        self.act_profil = QtWidgets.QAction(MainWindowInterface)
        self.act_profil.setObjectName("act_profil")
        self.act_close = QtWidgets.QAction(MainWindowInterface)
        self.act_close.setObjectName("act_close")
        self.act_settings = QtWidgets.QAction(MainWindowInterface)
        self.act_settings.setObjectName("act_settings")
        self.menu.addAction(self.act_settings)
        self.menu.addAction(self.act_rooms)
        self.menu.addAction(self.act_users)
        self.menu.addAction(self.act_profil)
        self.menu.addSeparator()
        self.menu.addAction(self.act_about)
        self.menu.addAction(self.act_close)
        self.menu_bar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindowInterface)
        self.tab_widget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindowInterface)
        MainWindowInterface.setTabOrder(self.check_box_mute, self.line_edit_search_rooms)
        MainWindowInterface.setTabOrder(self.line_edit_search_rooms, self.list_of_users)
        MainWindowInterface.setTabOrder(self.list_of_users, self.push_button_call)
        MainWindowInterface.setTabOrder(self.push_button_call, self.line_edit_search_users)
        MainWindowInterface.setTabOrder(self.line_edit_search_users, self.tab_widget)
        MainWindowInterface.setTabOrder(self.tab_widget, self.list_of_rooms)

    def retranslateUi(self, MainWindowInterface):
        _translate = QtCore.QCoreApplication.translate
        MainWindowInterface.setWindowTitle(_translate("MainWindowInterface", "JaroEliCall"))
        self.label_selected.setText(_translate("MainWindowInterface", "TextLabel"))
        self.line_edit_search_users.setPlaceholderText(_translate("MainWindowInterface", "Wyszukaj"))
        self.list_of_users.setSortingEnabled(True)
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab_users), _translate("MainWindowInterface", "Użytkownicy"))
        self.line_edit_search_rooms.setPlaceholderText(_translate("MainWindowInterface", "Wyszukaj"))
        self.list_of_rooms.setSortingEnabled(True)
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab_rooms), _translate("MainWindowInterface", "Pokoje"))
        self.push_button_call.setText(_translate("MainWindowInterface", "Zadzwoń"))
        self.check_box_mute.setText(_translate("MainWindowInterface", "Wycisz mikrofon"))
        self.label_you_logged_as.setText(_translate("MainWindowInterface", "Zalogowany jako:"))
        self.label_user_name.setText(_translate("MainWindowInterface", "Użyszkodnik"))
        self.menu.setTitle(_translate("MainWindowInterface", "&Menu"))
        self.act_about.setText(_translate("MainWindowInterface", "&O aplikacji"))
        self.actionUstawienia.setText(_translate("MainWindowInterface", "&Ustawienia"))
        self.act_rooms.setText(_translate("MainWindowInterface", "&Pokoje"))
        self.act_users.setText(_translate("MainWindowInterface", "Uż&ytkownicy"))
        self.act_profil.setText(_translate("MainWindowInterface", "P&rofil"))
        self.act_close.setText(_translate("MainWindowInterface", "&Zakończ"))
        self.act_settings.setText(_translate("MainWindowInterface", "&Ustawienia"))

