# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/afar/Dokumenty/Project_IP_Telephony_Python_Voip/JaroEliCall/gui/ui/main.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainInterfaceDialog(object):
    def setupUi(self, MainInterfaceDialog):
        MainInterfaceDialog.setObjectName("MainInterfaceDialog")
        MainInterfaceDialog.setWindowModality(QtCore.Qt.NonModal)
        MainInterfaceDialog.resize(757, 683)
        MainInterfaceDialog.setMinimumSize(QtCore.QSize(0, 0))
        self.gridLayout_2 = QtWidgets.QGridLayout(MainInterfaceDialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.grid_layout = QtWidgets.QGridLayout()
        self.grid_layout.setObjectName("grid_layout")
        self.label_list_users = QtWidgets.QLabel(MainInterfaceDialog)
        self.label_list_users.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_list_users.setIndent(4)
        self.label_list_users.setObjectName("label_list_users")
        self.grid_layout.addWidget(self.label_list_users, 1, 0, 1, 2)
        self.table_widget_list_of_users = QtWidgets.QTableWidget(MainInterfaceDialog)
        self.table_widget_list_of_users.setMinimumSize(QtCore.QSize(600, 100))
        self.table_widget_list_of_users.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.table_widget_list_of_users.setBaseSize(QtCore.QSize(100, 20))
        self.table_widget_list_of_users.setAutoFillBackground(False)
        self.table_widget_list_of_users.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.table_widget_list_of_users.setMidLineWidth(1)
        self.table_widget_list_of_users.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.table_widget_list_of_users.setAutoScroll(False)
        self.table_widget_list_of_users.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.table_widget_list_of_users.setDragDropOverwriteMode(False)
        self.table_widget_list_of_users.setAlternatingRowColors(False)
        self.table_widget_list_of_users.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.table_widget_list_of_users.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.table_widget_list_of_users.setIconSize(QtCore.QSize(20, 20))
        self.table_widget_list_of_users.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.table_widget_list_of_users.setShowGrid(True)
        self.table_widget_list_of_users.setObjectName("table_widget_list_of_users")
        self.table_widget_list_of_users.setColumnCount(3)
        self.table_widget_list_of_users.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_widget_list_of_users.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_widget_list_of_users.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setText("Awatar")
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.table_widget_list_of_users.setHorizontalHeaderItem(2, item)
        self.table_widget_list_of_users.horizontalHeader().setCascadingSectionResizes(True)
        self.table_widget_list_of_users.horizontalHeader().setDefaultSectionSize(100)
        self.table_widget_list_of_users.horizontalHeader().setMinimumSectionSize(100)
        self.table_widget_list_of_users.horizontalHeader().setStretchLastSection(True)
        self.table_widget_list_of_users.verticalHeader().setMinimumSectionSize(100)
        self.grid_layout.addWidget(self.table_widget_list_of_users, 2, 0, 1, 2)
        self.push_button_call = QtWidgets.QPushButton(MainInterfaceDialog)
        self.push_button_call.setObjectName("push_button_call")
        self.grid_layout.addWidget(self.push_button_call, 3, 0, 1, 1)
        self.push_button_invite = QtWidgets.QPushButton(MainInterfaceDialog)
        self.push_button_invite.setEnabled(False)
        self.push_button_invite.setToolTipDuration(3)
        self.push_button_invite.setStatusTip("")
        self.push_button_invite.setObjectName("push_button_invite")
        self.grid_layout.addWidget(self.push_button_invite, 3, 1, 1, 1)
        self.vertical_layout_top = QtWidgets.QVBoxLayout()
        self.vertical_layout_top.setObjectName("vertical_layout_top")
        self.grid_layout.addLayout(self.vertical_layout_top, 0, 0, 1, 2)
        self.vertical_layout_right = QtWidgets.QVBoxLayout()
        self.vertical_layout_right.setObjectName("vertical_layout_right")
        self.label_avatar = QtWidgets.QLabel(MainInterfaceDialog)
        self.label_avatar.setMinimumSize(QtCore.QSize(75, 75))
        self.label_avatar.setMaximumSize(QtCore.QSize(100, 100))
        self.label_avatar.setBaseSize(QtCore.QSize(5, 5))
        self.label_avatar.setText("")
        self.label_avatar.setPixmap(QtGui.QPixmap(":/avatars/astronaut.png"))
        self.label_avatar.setScaledContents(True)
        self.label_avatar.setObjectName("label_avatar")
        self.vertical_layout_right.addWidget(self.label_avatar)
        self.label_user_name = QtWidgets.QLabel(MainInterfaceDialog)
        self.label_user_name.setAlignment(QtCore.Qt.AlignCenter)
        self.label_user_name.setObjectName("label_user_name")
        self.vertical_layout_right.addWidget(self.label_user_name)
        self.push_button_logout = QtWidgets.QPushButton(MainInterfaceDialog)
        self.push_button_logout.setObjectName("push_button_logout")
        self.vertical_layout_right.addWidget(self.push_button_logout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.vertical_layout_right.addItem(spacerItem)
        self.grid_layout.addLayout(self.vertical_layout_right, 1, 3, 3, 1)
        spacerItem1 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.grid_layout.addItem(spacerItem1, 1, 2, 3, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.grid_layout.addItem(spacerItem2, 1, 4, 3, 1)
        self.vertical_layout_left = QtWidgets.QVBoxLayout()
        self.vertical_layout_left.setObjectName("vertical_layout_left")
        self.grid_layout.addLayout(self.vertical_layout_left, 4, 0, 1, 2)
        self.gridLayout_2.addLayout(self.grid_layout, 0, 0, 1, 1)

        self.retranslateUi(MainInterfaceDialog)
        QtCore.QMetaObject.connectSlotsByName(MainInterfaceDialog)
        MainInterfaceDialog.setTabOrder(self.table_widget_list_of_users, self.push_button_call)
        MainInterfaceDialog.setTabOrder(self.push_button_call, self.push_button_invite)
        MainInterfaceDialog.setTabOrder(self.push_button_invite, self.push_button_logout)

    def retranslateUi(self, MainInterfaceDialog):
        _translate = QtCore.QCoreApplication.translate
        MainInterfaceDialog.setWindowTitle(_translate("MainInterfaceDialog", "JaroEliCall"))
        self.label_list_users.setText(_translate("MainInterfaceDialog", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">Lista użytkowników</span></p></body></html>"))
        self.table_widget_list_of_users.setSortingEnabled(True)
        item = self.table_widget_list_of_users.horizontalHeaderItem(0)
        item.setText(_translate("MainInterfaceDialog", "Kto"))
        item = self.table_widget_list_of_users.horizontalHeaderItem(1)
        item.setText(_translate("MainInterfaceDialog", "Status"))
        self.push_button_call.setText(_translate("MainInterfaceDialog", "Zadzwoń"))
        self.push_button_invite.setToolTip(_translate("MainInterfaceDialog", "Funkcja aktualnie niedostępna"))
        self.push_button_invite.setText(_translate("MainInterfaceDialog", "Zaproś do pokoju"))
        self.label_user_name.setText(_translate("MainInterfaceDialog", "User name"))
        self.push_button_logout.setText(_translate("MainInterfaceDialog", "Wyloguj"))

