# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/afar/Dokumenty/Project_IP_Telephony_Python_Voip/JaroEliCall/gui/ui/password_change.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_LoginInterfaceDialog(object):
    def setupUi(self, LoginInterfaceDialog):
        LoginInterfaceDialog.setObjectName("LoginInterfaceDialog")
        LoginInterfaceDialog.resize(408, 201)
        LoginInterfaceDialog.setMinimumSize(QtCore.QSize(0, 0))
        LoginInterfaceDialog.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.gridLayout = QtWidgets.QGridLayout(LoginInterfaceDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_form_name = QtWidgets.QLabel(LoginInterfaceDialog)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_form_name.setFont(font)
        self.label_form_name.setAlignment(QtCore.Qt.AlignCenter)
        self.label_form_name.setObjectName("label_form_name")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.label_form_name)
        self.label_login = QtWidgets.QLabel(LoginInterfaceDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_login.sizePolicy().hasHeightForWidth())
        self.label_login.setSizePolicy(sizePolicy)
        self.label_login.setMinimumSize(QtCore.QSize(45, 0))
        self.label_login.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_login.setObjectName("label_login")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_login)
        self.line_edit_login = QtWidgets.QLineEdit(LoginInterfaceDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_edit_login.sizePolicy().hasHeightForWidth())
        self.line_edit_login.setSizePolicy(sizePolicy)
        self.line_edit_login.setMinimumSize(QtCore.QSize(0, 0))
        self.line_edit_login.setMaxLength(20)
        self.line_edit_login.setObjectName("line_edit_login")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.line_edit_login)
        self.label_password = QtWidgets.QLabel(LoginInterfaceDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_password.sizePolicy().hasHeightForWidth())
        self.label_password.setSizePolicy(sizePolicy)
        self.label_password.setMinimumSize(QtCore.QSize(45, 0))
        self.label_password.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_password.setObjectName("label_password")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_password)
        self.line_edit_password = QtWidgets.QLineEdit(LoginInterfaceDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_edit_password.sizePolicy().hasHeightForWidth())
        self.line_edit_password.setSizePolicy(sizePolicy)
        self.line_edit_password.setMinimumSize(QtCore.QSize(0, 0))
        self.line_edit_password.setMaxLength(20)
        self.line_edit_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.line_edit_password.setObjectName("line_edit_password")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.line_edit_password)
        self.label_repeat_password = QtWidgets.QLabel(LoginInterfaceDialog)
        self.label_repeat_password.setObjectName("label_repeat_password")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_repeat_password)
        self.line_edit_repeat_password = QtWidgets.QLineEdit(LoginInterfaceDialog)
        self.line_edit_repeat_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.line_edit_repeat_password.setObjectName("line_edit_repeat_password")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.line_edit_repeat_password)
        self.horizontal_layout_5 = QtWidgets.QHBoxLayout()
        self.horizontal_layout_5.setSpacing(2)
        self.horizontal_layout_5.setObjectName("horizontal_layout_5")
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontal_layout_5.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontal_layout_5.addItem(spacerItem1)
        self.push_button_change_password = QtWidgets.QPushButton(LoginInterfaceDialog)
        self.push_button_change_password.setObjectName("push_button_change_password")
        self.horizontal_layout_5.addWidget(self.push_button_change_password)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontal_layout_5.addItem(spacerItem2)
        self.formLayout.setLayout(5, QtWidgets.QFormLayout.SpanningRole, self.horizontal_layout_5)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(0, QtWidgets.QFormLayout.SpanningRole, spacerItem3)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(6, QtWidgets.QFormLayout.SpanningRole, spacerItem4)
        self.gridLayout.addLayout(self.formLayout, 1, 0, 1, 1)

        self.retranslateUi(LoginInterfaceDialog)
        QtCore.QMetaObject.connectSlotsByName(LoginInterfaceDialog)
        LoginInterfaceDialog.setTabOrder(self.line_edit_login, self.line_edit_password)
        LoginInterfaceDialog.setTabOrder(self.line_edit_password, self.push_button_change_password)

    def retranslateUi(self, LoginInterfaceDialog):
        _translate = QtCore.QCoreApplication.translate
        LoginInterfaceDialog.setWindowTitle(_translate("LoginInterfaceDialog", "Dialog"))
        self.label_form_name.setText(_translate("LoginInterfaceDialog", "Zmiana hasła"))
        self.label_login.setText(_translate("LoginInterfaceDialog", "Login:"))
        self.label_password.setText(_translate("LoginInterfaceDialog", "Hasło:"))
        self.label_repeat_password.setText(_translate("LoginInterfaceDialog", "Powtórz hasło:"))
        self.push_button_change_password.setText(_translate("LoginInterfaceDialog", "Zmień hasło"))

