# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/afar/Dokumenty/Project_IP_Telephony_Python_Voip/JaroEliCall/gui/ui/password_change.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ActivationInterfaceDialog(object):
    def setupUi(self, ActivationInterfaceDialog):
        ActivationInterfaceDialog.setObjectName("ActivationInterfaceDialog")
        ActivationInterfaceDialog.resize(615, 367)
        ActivationInterfaceDialog.setMinimumSize(QtCore.QSize(0, 0))
        ActivationInterfaceDialog.setMaximumSize(QtCore.QSize(615, 370))
        self.gridLayout = QtWidgets.QGridLayout(ActivationInterfaceDialog)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 3, 1, 1)
        self.label_form_name = QtWidgets.QLabel(ActivationInterfaceDialog)
        self.label_form_name.setMinimumSize(QtCore.QSize(400, 0))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_form_name.setFont(font)
        self.label_form_name.setAlignment(QtCore.Qt.AlignCenter)
        self.label_form_name.setObjectName("label_form_name")
        self.gridLayout.addWidget(self.label_form_name, 0, 2, 1, 1)
        self.vertical_layout_1 = QtWidgets.QVBoxLayout()
        self.vertical_layout_1.setContentsMargins(-1, 9, -1, -1)
        self.vertical_layout_1.setSpacing(6)
        self.vertical_layout_1.setObjectName("vertical_layout_1")
        self.label_avatar = QtWidgets.QLabel(ActivationInterfaceDialog)
        self.label_avatar.setMinimumSize(QtCore.QSize(100, 100))
        self.label_avatar.setMaximumSize(QtCore.QSize(100, 100))
        self.label_avatar.setText("")
        self.label_avatar.setPixmap(QtGui.QPixmap("../resources/avatars/detective.png"))
        self.label_avatar.setScaledContents(True)
        self.label_avatar.setAlignment(QtCore.Qt.AlignCenter)
        self.label_avatar.setIndent(0)
        self.label_avatar.setObjectName("label_avatar")
        self.vertical_layout_1.addWidget(self.label_avatar)
        self.label_avatar_name = QtWidgets.QLabel(ActivationInterfaceDialog)
        self.label_avatar_name.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_avatar_name.setAlignment(QtCore.Qt.AlignCenter)
        self.label_avatar_name.setObjectName("label_avatar_name")
        self.vertical_layout_1.addWidget(self.label_avatar_name)
        self.push_button_avatar = QtWidgets.QPushButton(ActivationInterfaceDialog)
        self.push_button_avatar.setObjectName("push_button_avatar")
        self.vertical_layout_1.addWidget(self.push_button_avatar)
        self.gridLayout.addLayout(self.vertical_layout_1, 0, 1, 1, 1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setContentsMargins(-1, -1, 9, 18)
        self.formLayout.setObjectName("formLayout")
        self.label_login = QtWidgets.QLabel(ActivationInterfaceDialog)
        self.label_login.setMinimumSize(QtCore.QSize(100, 0))
        self.label_login.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_login.setObjectName("label_login")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_login)
        self.line_edit_login = QtWidgets.QLineEdit(ActivationInterfaceDialog)
        self.line_edit_login.setMaxLength(30)
        self.line_edit_login.setObjectName("line_edit_login")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.line_edit_login)
        self.label_password = QtWidgets.QLabel(ActivationInterfaceDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_password.sizePolicy().hasHeightForWidth())
        self.label_password.setSizePolicy(sizePolicy)
        self.label_password.setMinimumSize(QtCore.QSize(100, 0))
        self.label_password.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_password.setObjectName("label_password")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_password)
        self.line_edit_password = QtWidgets.QLineEdit(ActivationInterfaceDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_edit_password.sizePolicy().hasHeightForWidth())
        self.line_edit_password.setSizePolicy(sizePolicy)
        self.line_edit_password.setMinimumSize(QtCore.QSize(0, 0))
        self.line_edit_password.setMaxLength(30)
        self.line_edit_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.line_edit_password.setObjectName("line_edit_password")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.line_edit_password)
        self.label_repeat_password = QtWidgets.QLabel(ActivationInterfaceDialog)
        self.label_repeat_password.setMinimumSize(QtCore.QSize(100, 0))
        self.label_repeat_password.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_repeat_password.setObjectName("label_repeat_password")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_repeat_password)
        self.line_edit_repeat_password = QtWidgets.QLineEdit(ActivationInterfaceDialog)
        self.line_edit_repeat_password.setMaxLength(30)
        self.line_edit_repeat_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.line_edit_repeat_password.setObjectName("line_edit_repeat_password")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.line_edit_repeat_password)
        self.horizontal_layout_5 = QtWidgets.QHBoxLayout()
        self.horizontal_layout_5.setContentsMargins(0, 18, 0, 0)
        self.horizontal_layout_5.setSpacing(0)
        self.horizontal_layout_5.setObjectName("horizontal_layout_5")
        self.push_button_change_password = QtWidgets.QPushButton(ActivationInterfaceDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.push_button_change_password.sizePolicy().hasHeightForWidth())
        self.push_button_change_password.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.push_button_change_password.setFont(font)
        self.push_button_change_password.setObjectName("push_button_change_password")
        self.horizontal_layout_5.addWidget(self.push_button_change_password)
        self.formLayout.setLayout(3, QtWidgets.QFormLayout.SpanningRole, self.horizontal_layout_5)
        self.gridLayout.addLayout(self.formLayout, 1, 1, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 0, 1, 1)

        self.retranslateUi(ActivationInterfaceDialog)
        QtCore.QMetaObject.connectSlotsByName(ActivationInterfaceDialog)

    def retranslateUi(self, ActivationInterfaceDialog):
        _translate = QtCore.QCoreApplication.translate
        ActivationInterfaceDialog.setWindowTitle(_translate("ActivationInterfaceDialog", "JaroEliCall  -  aktywacja konta"))
        self.label_form_name.setText(_translate("ActivationInterfaceDialog", "<html><head/><body><p>### Zmiana hasła ###</p></body></html>"))
        self.label_avatar_name.setText(_translate("ActivationInterfaceDialog", "Nazwa"))
        self.push_button_avatar.setText(_translate("ActivationInterfaceDialog", "Wybierz awatar"))
        self.label_login.setText(_translate("ActivationInterfaceDialog", "login"))
        self.label_password.setText(_translate("ActivationInterfaceDialog", "Hasło:"))
        self.label_repeat_password.setText(_translate("ActivationInterfaceDialog", "Powtórz hasło:"))
        self.push_button_change_password.setText(_translate("ActivationInterfaceDialog", "Ustaw hasło i avatar"))

